<!doctype html>
<html>
    <body>
        <?php
            if($_SERVER["REQUEST_METHOD"]=="POST")
            {
                ini_set('display_errors',1);
                define("INITIALIZING_DATABASE",1);
                require_once("db_conn.php");
                
                $pdo->query("drop database if exists cia");
                $pdo->query("create database cia");
                $pdo->query("use cia");
                
                $pdo->query("drop table if exists Secret");
                
                $pdo->query("create table Secret (
                        SecretId integer not null PRIMARY KEY AUTO_INCREMENT,
                        Description varchar(255) not null,
                        Tags varchar(255) not null,
                        Code varchar(20) not null,
                        SecretLevelId integer not null
                    )");
                
                $pdo->query(base64_decode("aW5zZXJ0IGludG8gU2VjcmV0IChEZXNjcmlwdGlvbixUYWdzLENvZGUsU2VjcmV0TGV2ZWxJZCkgdmFsdWVzIA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICgNCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgJzxiPklOU1RSVUNUSU9OUzogMSBNYXJrPC9iPiAtIEFkZCBDU1MgdG8gaGlkZSBlbGVtZW50cyB0aGF0IHVzZSB0aGUgc3R5bGUgY2xhc3MgImluc3RydWN0aW9ucyIuJywNCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgJ2V4YW0saW5zdHJ1Y3Rpb25zJywNCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgJ0VYQU0nLA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAzDQogICAgICAgICAgICAgICAgICAgICAgICAgICAgKSwNCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAoDQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICc8Yj5JTlNUUlVDVElPTlM6IDEgTWFyazwvYj4gLSBDcmVhdGUgYSBmdW5jdGlvbiB0byBjbGVhbiBhbmQgdmFsaWRhdGUgdGhlIHZhcmlhYmxlICRzZWFyY2hUZXJtLicsDQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICdleGFtLGluc3RydWN0aW9ucycsDQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICdFWEFNJywNCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgMw0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICksDQogICAgICAgICAgICAgICAgICAgICAgICAgICAgKA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAnPGI+SU5TVFJVQ1RJT05TOiAyIE1hcmtzPC9iPiAtIFVzZSBwcmVwYXJlZCBzdGF0ZW1lbnRzIHRvIHJldHJpZXZlIHRoZSBkYXRhLiBPbmx5IHJldHVybiByZWNvcmRzIHdoZXJlIHRoZSBkZXNjcmlwdGlvbiBjb250YWlucyB0aGUgdmFsdWUgb2YgJHNlYXJjaFRlcm0uJywNCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgJ2V4YW0saW5zdHJ1Y3Rpb25zJywNCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgJ0VYQU0nLA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAzDQogICAgICAgICAgICAgICAgICAgICAgICAgICAgKSwNCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAoDQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICdTRUNSRVQ6IElmIHlvdSBnZXQgdGhlIHNlYXJjaCBmdW5jdGlvbiB3b3JraW5nLCB5b3UgY2FuIGZpbHRlciB0aGUgcmVzdWx0cyB0byB2aWV3IG9ubHkgdGhlIGluc3RydWN0aW9ucyBvZiB0aGUgZXhhbS4nLA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAndGlwLHNlY3JldCcsDQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICdTRUFSQ0gnLA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAyDQogICAgICAgICAgICAgICAgICAgICAgICAgICAgKSwNCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAoDQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICc8Yj5JTlNUUlVDVElPTlM6IDEgTWFyazwvYj4gLSBXaGVuIGEgcG9zdCBpcyBtYWRlLCBtYWtlIHRoZSBzZWFyY2ggZmlsdGVyIHRleHRib3ggcmVtZW1iZXIgdGhlIHZhbHVlIHRoYXQgd2FzIGluIGl0LiAnLA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAnZXhhbSxpbnN0cnVjdGlvbnMnLA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAnRVhBTScsDQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDMNCiAgICAgICAgICAgICAgICAgICAgICAgICAgICApLA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICgNCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgJzxiPklOU1RSVUNUSU9OUzogMiBNYXJrczwvYj4gLSBXaGVuIHByaW50aW5nIG91dCByb3cgZGF0YSwgdXNlIHN0YW5kYXJkIGZ1bmN0aW9ucyB0byBzYW5pdGl6ZSB0aGUgZGF0YSBiZWZvcmUgcHJpbnRpbmcgaXQuIFdoZW4gcHJpbnRpbmcgdGhlIGRlc2NyaXB0aW9uIGZpZWxkLCBhbGxvdyB0aGUgJmx0O2ImZ3Q7IGFuZCAmbHQ7YnImZ3Q7IHRhZ3MgdG8gcmVtYWluIGludGFjdC4nLA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAnZXhhbSxpbnN0cnVjdGlvbnMnLA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAnRVhBTScsDQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDMNCiAgICAgICAgICAgICAgICAgICAgICAgICAgICApLA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICgNCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgJ1NFQ1JFVDogVUZPcyBhcmUgc3B5IGRyb25lcy4nLA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAnY29uc3BpcmFjeSxnb3Zlcm5tZW50LHNweScsDQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICdVRk8nLA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAyDQogICAgICAgICAgICAgICAgICAgICAgICAgICAgKSwNCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAoDQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICdXaGVuIENodWNrIE5vcnJpcyBnb2VzIGluIHdhdGVyLCBDaHVjayBOb3JyaXMgZG9lc24nJ3QgZ2V0IHdldC4gV2F0ZXIgZ2V0cyBDaHVjayBOb3JyaXMuJywNCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgJ2NvbW1vbiBzZW5zZSxvZiBjb3Vyc2UnLA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAnQ0hVQ0snLA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAxDQogICAgICAgICAgICAgICAgICAgICAgICAgICAgKSwNCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAoDQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICc8Yj5JTlNUUlVDVElPTlM6IDEgTWFya3M8L2I+IC0gV3JpdGUgYSByZWd1bGFyIGV4cHJlc3Npb24gdGhhdCBjaGVja3MgaWYgdGhlIGRlc2NyaXB0aW9uIGNvbnRhaW5zIGEgbnVtYmVyIGZvbGxvd2VkIGJ5IGEgc3BhY2UgYW5kIHRoZSB3b3JkIE1hcmsuIElmIHNvLCBzZXQgdGhlICRyZWNvcmRDb2xvciB2YXJpYWJsZSB0byAiYmlzcXVlIi4nLA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAnZXhhbSxpbnN0cnVjdGlvbnMnLA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAnRVhBTScsDQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDMNCiAgICAgICAgICAgICAgICAgICAgICAgICAgICApLA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICgNCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgJ0hBQ0tFRCE8c2NyaXB0PmhhY2tlZCgpPC9zY3JpcHQ+JywNCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgJ2JvZ3VzLGhhY2tlZCcsDQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICdIQUNLJywNCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgMg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICksDQogICAgICAgICAgICAgICAgICAgICAgICAgICAgKA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAnU0VDUkVUOiBZb3VyIGNlbGwgcGhvbmUgaXMgbGlzdGVuaW5nIHRvIHlvdS4nLA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAnY29uc3BpcmFjeSxnb3Zlcm5tZW50LHNweScsDQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICdQSE9ORScsDQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDINCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAp"));
                
                echo "<h3>Database Initialized</h3>";
            }
        ?>
        <form method="POST">
            <input type="submit" value="Initialize Database">
        </form>
    </body>
</html>






